import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Developer Docs — SimpleAgent",
  description: "Feature documentation for the SimpleAgent demo: what's mocked, what's real in production, and integration notes.",
};

const features = [
  {
    name: "Agent Catalog",
    location: "/demo → Agent Catalog tab",
    description: "Browse 15 pre-built single-task agent templates organized by category (Sales, Operations, Reputation, etc.).",
    tryIt: "Click category filters, then 'Activate' or 'Details' on any agent card. Active agents show a green badge.",
    mocked: "Agent list, pricing, and activation state are hardcoded in lib/mockData.ts. Toggling active/paused updates React state only.",
    production: "Templates stored as JSON configs in Supabase. Stripe subscription created on activation. Agent config deployed to serverless runtime (Vercel cron or AWS Lambda). New templates built in batch — 2-3 hours each, done once.",
    dataFlow: "User selects template → Stripe checkout → config saved to DB → agent worker provisioned → cron/webhook listener registered.",
  },
  {
    name: "Onboarding Wizard",
    location: "/demo → Onboarding Wizard tab",
    description: "4-step flow: choose agent, connect tools (Gmail/Outlook/CRM), set behavior (tone, delay, custom instructions), review & launch.",
    tryIt: "Walk through all 4 steps. Click 'Launch agent' on step 4 to see success screen and a new activity log entry.",
    mocked: "OAuth buttons show toasts instead of opening real OAuth. Integration selection and config are client-side state. 'Launch' adds a mock activity entry.",
    production: "OAuth 2.0 flows for Gmail (Google API), Outlook (Microsoft Graph), HubSpot. Config persisted to Supabase. Agent deployed via API call to worker service. Target: under 10 minutes end-to-end.",
    dataFlow: "OAuth callback → tokens encrypted in DB → agent config assembled → worker deployed → confirmation email via Resend.",
  },
  {
    name: "Activity Log",
    location: "/demo → Activity Log tab",
    description: "Plain-English feed of every agent action with timestamp, status, contact, company, and AI-generated reason.",
    tryIt: "Search by name/company, filter by status (completed/skipped/failed), click any row to open the detail modal.",
    mocked: "12 realistic entries in mockData.ts. Wizard completion prepends a new entry. Search and filters are client-side.",
    production: "Every agent run writes a log row to Supabase: { timestamp, agent_id, action, reason, status, metadata }. Reason generated by LLM at runtime. Real-time updates via polling or SSE.",
    dataFlow: "Agent executes action → LLM generates reason text → log row inserted → dashboard/API serves to frontend.",
  },
  {
    name: "Usage Dashboard",
    location: "/demo → Usage Dashboard tab",
    description: "Weekly stats, bar chart, per-agent breakdown table, and weekly email digest preview.",
    tryIt: "Toggle chart metrics (actions/emails/webhooks). Click 'Preview weekly digest' then 'Send test digest'. Pause agents from the table.",
    mocked: "Stats, chart data, and per-agent metrics are static mock data. Chart bars animate on metric toggle. Digest is a modal preview.",
    production: "Metrics aggregated hourly from agent run logs. Chart powered by Recharts. Weekly digest cron (Sunday 8am per timezone) sends templated email via Resend with activity summary.",
    dataFlow: "Agent runs → metrics table updated → dashboard queries aggregates → Resend cron reads weekly rollup → email sent.",
  },
  {
    name: "Webhooks & Connectors",
    location: "/demo → Webhooks & Connectors tab",
    description: "Outbound webhook URL for Zapier/Make, connected services management, and webhook delivery log.",
    tryIt: "Switch Zapier/Make tabs, copy webhook URL, send test event, connect/disconnect services, view delivery log.",
    mocked: "Webhook URL is editable text. Test event shows a modal with sample JSON. Connect/disconnect toggles local state. Delivery log is static.",
    production: "Unique webhook URL per customer (HMAC-signed payloads). Outbound POST on agent events. Inbound webhooks trigger agent runs. Zapier/Make use standard webhook triggers. Retry logic with exponential backoff on 5xx.",
    dataFlow: "Agent event → webhook dispatcher → POST to customer URL → delivery logged → retry on failure. Inbound: external POST → validate signature → queue agent run.",
  },
  {
    name: "Weekly Email Digest",
    location: "/demo → Usage Dashboard → 'Preview weekly digest' button",
    description: "Templated email summary of weekly agent activity with highlights and per-agent stats.",
    tryIt: "Click 'Preview weekly digest' on the dashboard, review content, click 'Send test digest'.",
    mocked: "Digest content from digestPreview in mockData.ts. 'Send test' shows a toast.",
    production: "Resend API sends HTML email from template. Cron job runs weekly. Template includes: total actions, top agent, highlights, link to full dashboard. No manual writing.",
    dataFlow: "Sunday cron → query weekly aggregates → render Resend template → send to account email → log delivery status.",
  },
  {
    name: "DEV NOTE Tooltips",
    location: "Throughout /demo — amber 'i' icons",
    description: "Info badges beside major controls explaining production behavior.",
    tryIt: "Click any amber 'i' icon next to section headings or buttons.",
    mocked: "Tooltip content is hardcoded in component JSX.",
    production: "These would be removed in production or replaced with inline help docs / Intercom tooltips.",
    dataFlow: "N/A — developer/reviewer feature only.",
  },
];

const architecture = [
  { layer: "Frontend", tech: "Next.js 14 App Router, Tailwind CSS, React state", note: "This demo — zero backend" },
  { layer: "Auth", tech: "Clerk or NextAuth + Google OAuth", note: "Not implemented in demo" },
  { layer: "Database", tech: "Supabase (Postgres)", note: "Agent configs, logs, user accounts" },
  { layer: "Agent runtime", tech: "Vercel cron + serverless functions", note: "Or AWS Lambda with EventBridge" },
  { layer: "AI", tech: "OpenAI Assistants API / GPT-4o", note: "Action decisions + reason generation" },
  { layer: "Email", tech: "Resend", note: "Agent emails + weekly digest" },
  { layer: "Billing", tech: "Stripe Billing", note: "Subscriptions, dunning, cancellations" },
  { layer: "Support", tech: "Intercom bot + Slack escalations", note: "~80% auto-resolved" },
  { layer: "Integrations", tech: "OAuth + webhooks + Zapier/Make", note: "Gmail, Outlook, HubSpot, QuickBooks" },
];

export default function DevelopersPage() {
  return (
    <div className="py-16">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12">
          <p className="text-sm font-semibold uppercase tracking-wider text-brand-400">Developer documentation</p>
          <h1 className="mt-2 font-display text-4xl font-bold text-white">SimpleAgent Demo — Feature Map</h1>
          <p className="mt-4 text-lg text-slate-400">
            Every feature in the interactive demo, what&apos;s mocked vs. production, and where to click to try it.
          </p>
          <Link href="/demo" className="btn-primary mt-6 inline-flex text-sm">
            Open the demo
          </Link>
        </div>

        <div className="space-y-8">
          {features.map((feature) => (
            <div key={feature.name} className="glass-card overflow-hidden">
              <div className="border-b border-white/10 bg-surface-700/30 px-6 py-4">
                <h2 className="font-display text-xl font-semibold text-white">{feature.name}</h2>
                <p className="mt-1 text-sm text-brand-400">{feature.location}</p>
              </div>
              <div className="space-y-4 px-6 py-5">
                <p className="text-sm text-slate-300">{feature.description}</p>

                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400">How to try it</h3>
                  <p className="mt-1 text-sm text-slate-400">{feature.tryIt}</p>
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="rounded-lg bg-amber-500/5 border border-amber-500/20 p-4">
                    <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400">Mocked in demo</h3>
                    <p className="mt-1 text-sm text-slate-400">{feature.mocked}</p>
                  </div>
                  <div className="rounded-lg bg-brand-500/5 border border-brand-500/20 p-4">
                    <h3 className="text-xs font-bold uppercase tracking-wider text-brand-400">Production plan</h3>
                    <p className="mt-1 text-sm text-slate-400">{feature.production}</p>
                  </div>
                </div>

                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Intended data flow</h3>
                  <p className="mt-1 text-sm text-slate-400">{feature.dataFlow}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16">
          <h2 className="font-display text-2xl font-bold text-white">Production architecture</h2>
          <p className="mt-2 text-sm text-slate-400">MVP estimate: 3 weeks with Next.js + Supabase + OpenAI + Resend</p>
          <div className="mt-6 overflow-hidden rounded-xl border border-white/10">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 bg-surface-700/30 text-left text-slate-400">
                  <th className="px-6 py-3 font-medium">Layer</th>
                  <th className="px-6 py-3 font-medium">Technology</th>
                  <th className="px-6 py-3 font-medium">Notes</th>
                </tr>
              </thead>
              <tbody>
                {architecture.map((row) => (
                  <tr key={row.layer} className="border-b border-white/5">
                    <td className="px-6 py-3 font-medium text-white">{row.layer}</td>
                    <td className="px-6 py-3 text-brand-300">{row.tech}</td>
                    <td className="px-6 py-3 text-slate-400">{row.note}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="mt-12 rounded-xl border border-white/10 bg-surface-800/50 p-6">
          <h2 className="font-display text-lg font-semibold text-white">Deploy notes</h2>
          <ul className="mt-3 space-y-2 text-sm text-slate-400">
            <li>• This demo requires zero environment variables and deploys to Vercel with no configuration.</li>
            <li>• All interactivity is client-side React state with hardcoded data in <code className="text-brand-300">lib/mockData.ts</code>.</li>
            <li>• No API routes, no database, no auth — pure static + client-side rendering.</li>
            <li>• Run <code className="text-brand-300">npm run build</code> to verify production build before deploy.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
